version: '3'

services:
  contentgeo-mcp:
    build:
      context: ../contentgeo_mcp
      dockerfile: Dockerfile.mcp
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  travel-blog:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - contentgeo-mcp 